//
//  WordCard.swift
//  IdeaBank
//
//  Created by シェイミ on 11/01/2023.
//

import SwiftUI

// MARK: Sample Message Model
struct Word: Identifiable, Equatable {
    var id: String = UUID().uuidString
    var word: String
    var description: String

    static var exampleWords = [
        Word(word: "Monkey", description: "A kind of simian"),
        Word(word: "Banana", description: "Fruit that a monkey likes to eat"),
        Word(word: "Chicken", description: "Everyone's favourite snack"),
        Word(word: "ExtremlyLongWord", description: "A really long word that is used for testing UI"),
        Word(word: "AnotherVeryLongWord", description: "You get the idea"),
        Word(word: "Contrary", description: "Ppposite in nature, direction, or meaning."),
        Word(word: "Cantankerous", description: "A description of myself in the morning"),
        Word(word: "University", description: "A high-level educational institution in which students study for degrees and academic research is done."),
        Word(word: "Professor", description: "A university academic of the highest rank; the holder of a university chair."),
        Word(word: "Message", description: "A verbal, written, or recorded communication sent to or left for a recipient who cannot be contacted directly."),
        Word(word: "Shy", description: "Nervous or timid in the company of other people."),
        Word(word: "Food", description: "Something we all love"),
        Word(word: "Educator", description: "A person who provides instruction or education; a teacher."),
        Word(word: "Fitness Instructor", description: "Someone whose job is to help other people improve fitness"),
        Word(word: "Number", description: "An arithmetical value, expressed by a word, symbol, or figure"),
        Word(word: "Anxiety", description: "A feeling you get when your codes is being reviewed."),
        Word(word: "Cook", description: "To prepare something by mixing, combining, and heating the ingredients."),
        Word(word: "Hairdresser", description: "A person who makes your hair looks pretty"),
        Word(word: "Pressure", description: "The thing you feel when your mentor is watching you code."),
        Word(word: "Engineering", description: "The action of working artfully to bring something about."),
        Word(word: "Artist", description: "A person who perform art or specializes in artistic ways."),
        Word(word: "Manager", description: "A human being who likes to give you a lot of tasks and rush you."),
        Word(word: "Tax", description: "A thing we have to pay to the gov but sometimes complain about."),
        Word(word: "Healthcare", description: "The organized provision of medical care to individuals or a community."),
        Word(word: "Planner", description: "A person who makes plan for everything."),
        Word(word: "IT Specialist", description: "A geek who is so good at Information and Technology stuff."),
        Word(word: "Birthday", description: "The day you get lots of present and have an excuse to throw tantrums without being scolded."),
        Word(word: "Scientist", description: "A person who is studying or has expert knowledge of one or more of the natural or physical sciences."),
        Word(word: "Receptionist", description: "A pretty lady or handsome guy who usually stands or sit at the reception."),
        Word(word: "Actor", description: "A person whose profession is to do whatever the scripts tell him to in front of cameras and lots of people."),
        Word(word: "Book", description: "The thing we hate when it has something to do with school but enjoy reading when it has fictions."),
        Word(word: "Photographer", description: "A person who makes a living by taking pretty awesome photos."),
        Word(word: "Mathematician", description: "An alien who loves to do complex mathematical calculations."),
        Word(word: "Writer", description: "A person who write fictions or non-fictions to make our world more colorful."),
        Word(word: "Cylinder", description: "A pringles can without lid and bottom."),
        Word(word: "Therapist", description: "A person skilled in a particular kind of therapy."),
        Word(word: "Software Developer", description: "Super awesome human beings who create computer programs."),
        Word(word: "Electrician", description: "A person who installs and maintains electrical equipment."),
        Word(word: "Settle", description: "Resolve or reach an agreement about"),
        Word(word: "Lake", description: "Very very very small sea."),
        Word(word: "Need", description: "Require (something)."),
        Word(word: "Depression", description: "Feelings of severe despondency and dejection."),
        Word(word: "Mention", description: "A reference to someone or something."),
        Word(word: "Sunrise", description: "A moment we never really get to enjoy because we are sleeping till noon."),
        Word(word: "Monster", description: "The scary thing from horro movies and under your bed."),
        Word(word: "Packet", description: "A paper or cardboard container."),
        Word(word: "Rocket", description: "A cylindrical projectile that can be propelled to a great height or distance by the combustion of its contents"),
        Word(word: "Sticky", description: "The conditions of your hands after you hold the candy in your hands under the hot sun."),
        Word(word: "Tea", description: "A drink that is not coffee."),
        Word(word: "Fresh", description: "New"),
        Word(word: "Leftover", description: "Food you put inside the refrigerator when you can finish all."),
        Word(word: "Quote", description: "A really cool sentence we copy from books or movies to make ourselves sound smart."),
        Word(word: "Get", description: "An http method"),
        Word(word: "Modify", description: "Change or update something."),
        Word(word: "Highlight", description: "Draw special attention to."),
        Word(word: "Gather", description: "Come together/Asemble"),
        Word(word: "Lack", description: "Be without"),
        Word(word: "Attract", description: "Cause (someone) to have a liking for or interest in something."),
        Word(word: "Push", description: "A verb you usually get confused with pull when it's on the door."),
        Word(word: "Attach", description: "lorem ipsum"),
        Word(word: "Question", description: "lorem ipsum"),
        Word(word: "Smile", description: "lorem ipsum"),
        Word(word: "Reach", description: "lorem ipsum"),
        Word(word: "Examine", description: "lorem ipsum"),
        Word(word: "Hope", description: "lorem ipsum"),
        Word(word: "Guarantee", description: "lorem ipsum"),
        Word(word: "Fall", description: "lorem ipsum"),
        Word(word: "Hope", description: "lorem ipsum"),
        Word(word: "Fit", description: "lorem ipsum"),
        Word(word: "Catch", description: "lorem ipsum"),
        Word(word: "Heat", description: "lorem ipsum"),
        Word(word: "Transmit", description: "lorem ipsum"),
        Word(word: "Visit", description: "lorem ipsum"),
        Word(word: "Worry", description: "lorem ipsum"),
        Word(word: "Characterise", description: "lorem ipsum"),
        Word(word: "Communicate", description: "lorem ipsum"),
        Word(word: "Track", description: "lorem ipsum"),
        Word(word: "Waste", description: "lorem ipsum"),
        Word(word: "Clear", description: "lorem ipsum"),
        Word(word: "Allow", description: "lorem ipsum"),
        Word(word: "Start", description: "lorem ipsum"),
        Word(word: "Mix", description: "lorem ipsum"),
        Word(word: "Entertain", description: "lorem ipsum"),
        Word(word: "Bound", description: "lorem ipsum"),
        Word(word: "Deny", description: "lorem ipsum"),
        Word(word: "Integrate", description: "lorem ipsum"),
        Word(word: "Link", description: "lorem ipsum"),
        Word(word: "Build", description: "lorem ipsum"),
        Word(word: "Pin", description: "lorem ipsum"),
        Word(word: "Rush", description: "lorem ipsum"),
        Word(word: "Determine", description: "lorem ipsum"),
        Word(word: "Dictate", description: "lorem ipsum"),
        Word(word: "Discharge", description: "lorem ipsum"),
        Word(word: "Furry", description: "lorem ipsum"),
        Word(word: "Suitable", description: "lorem ipsum"),
        Word(word: "Every", description: "lorem ipsum"),
        Word(word: "Hard", description: "lorem ipsum"),
        Word(word: "Nostalgic", description: "lorem ipsum"),
        Word(word: "Amusing", description: "lorem ipsum"),
        Word(word: "Sorry", description: "lorem ipsum"),
        Word(word: "Women", description: "lorem ipsum"),
        Word(word: "Bored", description: "lorem ipsum"),
        Word(word: "Plucky", description: "lorem ipsum"),
        Word(word: "Thoughtless", description: "lorem ipsum"),
        Word(word: "Descriptive", description: "lorem ipsum"),
        Word(word: "Even", description: "lorem ipsum"),
        Word(word: "Smoggy", description: "lorem ipsum"),
        Word(word: "Adaptable", description: "lorem ipsum"),
        Word(word: "Comfortable", description: "lorem ipsum"),
        Word(word: "Breezy", description: "lorem ipsum"),
        Word(word: "Sharp", description: "lorem ipsum"),
        Word(word: "Puny", description: "lorem ipsum"),
        Word(word: "Useless", description: "lorem ipsum"),
        Word(word: "Spare", description: "lorem ipsum"),
        Word(word: "Left", description: "lorem ipsum"),
        Word(word: "Lovely", description: "lorem ipsum"),
        Word(word: "Abrupt", description: "lorem ipsum"),
        Word(word: "Habitual", description: "lorem ipsum"),
        Word(word: "Panoramic", description: "lorem ipsum"),
        Word(word: "Tasteful", description: "lorem ipsum"),
        Word(word: "Harsh", description: "lorem ipsum"),
        Word(word: "Realistic", description: "lorem ipsum"),
        Word(word: "Standing", description: "lorem ipsum"),
        Word(word: "Funny", description: "lorem ipsum"),
        Word(word: "Unique", description: "lorem ipsum"),
        Word(word: "Polite", description: "lorem ipsum"),
        Word(word: "Tension", description: "lorem ipsum"),
        Word(word: "Crazy", description: "lorem ipsum"),
        Word(word: "Educated", description: "lorem ipsum"),
        Word(word: "Quiet", description: "lorem ipsum"),
        Word(word: "Sad", description: "lorem ipsum")
    ]
}
